### ISSUE TITLE
sxos emu11.0.0 Invalid nag magic detected

### ISSUE THREAD

**Issue by xfangfang** [Adubbz/Gag-Order#12]
I'm trying to modify the code to adapt to the latest libnx(because I can't use it on sxos emu11.0.0, the button doesn't respond) and run it on my sxos device (emu11.0.0), but I have a problem. The data read from my console is:

> 16080000 00000001 1400012C 03000000
> 00000000 000...

which is not pass the `NagMagic verify`

I don't know what the two data(`0x100000C8` and `0x14020028`)in the original code means ?

Could you help me?

**Comment by Adubbz** [comment]
Both of those are simply data present in the ns_ssversion save file that are different when consoles have been nagged versus unnagged. This tool swaps the data or nagged consoles for that on unnagged consoles. No effort was made to reverse engineer its actual format. Also note this only works on 4.1.0 and has not been updated to any subsequent firmware versions. I believe other tools have been developed now though I don't really know the details surrounding them.
I don't have any plans to update this further so for now I'm gonna close this.
